service: s3
provider:
  name: aws
  runtime: nodejs12.x
plugins:
  - serverless-s3-local
  - serverless-offline
custom:
  s3:
    host: localhost
    directory: /tmp
resources:
  Resources:
    UserBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: user-pictures
    PartyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: party-pictures
