export enum FeatureToggleName {
  MAILING = 'MAILING',

  SIGN_UP = 'SIGN_UP',

  USER_GET = 'USER_GET',
  USER_GET_FOLLOWING = 'USER_GET_FOLLOWING',
  USER_GET_FOLLOWERS = 'USER_GET_FOLLOWERS',
  USER_GET_ATTENDED_PARTIES = 'USER_GET_ATTENDED_PARTIES',
  USER_SEARCH_FOLLOWERS_TO_INVITE = 'USER_SEARCH_FOLLOWERS_TO_INVITE',
  USER_CHANGE_FOLLOWING_STATE = 'USER_CHANGE_FOLLOWING_STATE',
  USER_CHANGE_ATTENDING_STATE = 'USER_CHANGE_ATTENDING_STATE',
  USER_SEND_PARTY_INVITE = 'USER_SEND_PARTY_INVITE',
  USER_EDIT = 'USER_EDIT',
  USER_DELETE = 'USER_DELETE',

  NOTIFICATION_GET = 'NOTIFICATION_GET',

  PARTY_GET = 'PARTY_GET',
  PARTY_SEARCH_ATTENDERS = 'PARTY_SEARCH_ATTENDERS',
  PARTY_CREATE = 'PARTY_CREATE',
  PARTY_DELETE = 'PARTY_DELETE',
}

export type FeatureToggleMetadata = {
  names: Array<FeatureToggleName>;
};
