import * as bcrypt from 'bcrypt';
import { v4 } from 'uuid';
import { User } from '../schema';

export const mockUser = (data: Partial<User>): User => ({
  _id: v4(),
  email: 'juliangsibecas@gmail.com',
  nickname: 'juliangsibecas',
  fullName: 'Julian Gomez Sibecas',
  following: [],
  followers: [],
  attendedParties: [],
  attendedPartiesCount: 0,
  organizedParties: [],
  chats: [],
  invites: [],
  notifications: [],
  password: bcrypt.hashSync('1234', 1),
  createdAt: new Date(),
  ...data,
});

export const MOCKED_USERS = [
  mockUser({}),
  mockUser({
    email: 'gumpy@gmail.com',
    nickname: 'gumpy',
    fullName: 'Forest Gump',
  }),
  mockUser({
    email: 'cosmo@gmail.com',
    nickname: 'cosmo',
    fullName: 'Cosmo',
  }),
  mockUser({
    email: 'guayra@gmail.com',
    nickname: 'guarya',
    fullName: 'Guayra',
  }),
];

export const MOCKED_MALE_NAMES = [
  'Agustin',
  'Andres',
  'Bautista',
  'Benjamin',
  'Diego',
  'Esteban',
  'Facundo',
  'Fausto',
  'Fermin',
  'Francisco',
  'Franco',
  'Jeronimo',
  'Lorenzo',
  'Luciano',
  'Martin',
  'Mariano',
  'Manuel',
  'Matias',
  'Nicolas',
  'Octavio',
  'Pablo',
  'Pedro',
  'Rodrigo',
  'Tomas',
];

export const MOCKED_FEMALE_NAMES = [
  'Abril',
  'Agustina',
  'Agostina',
  'Azul',
  'Bianca',
  'Candela',
  'Carla',
  'Clara',
  'Celeste',
  'Francisca',
  'Jazmin',
  'Julia',
  'Julieta',
  'Josefina',
  'Laura',
  'Lorena',
  'Luz',
  'Maria',
  'Martina',
  'Micaela',
  'Milagros',
  'Paz',
  'Pilar',
  'Rocio',
  'Rosario',
  'Valentina',
];

export const MOCKED_SURENAMES = [
  'Aguilar',
  'Aguirre',
  'Alonso',
  'Alvarez',
  'Avila',
  'Bianchi',
  'Blanco',
  'Cabrera',
  'Caceres',
  'Castro',
  'Diaz',
  'Fernandez',
  'Ferrer',
  'Gimenez',
  'Godoy',
  'Gonzalez',
  'Gomez',
  'Herrera',
  'Iglesias',
  'Irigoyen',
  'Lombardi',
  'Lombardo',
  'Lopez',
  'Mansilla',
  'Marino',
  'Mendez',
  'Miranda',
  'Olivera',
  'Ortiz',
  'Paez',
  'Perez',
  'Ponce',
  'Roca',
  'Rossi',
  'Ramos',
  'Rodriguez',
  'Ruiz',
  'Serrano',
  'Silva',
  'Sosa',
  'Torres',
  'Varela',
];

export const MOCKED_MALE_FULL_NAMES = [
  'Agustin Miranda',
  'Andres Ortiz',
  'Bautista Ramos',
  'Benjamin Gonzalez',
  'Diego Silva',
  'Esteban Ferrer',
  'Facundo Cabrera',
  'Fausto Mendez',
  'Fermin Rodriguez',
  'Francisco Aguilar',
  'Franco Avila',
  'Jeronimo Alvarez',
  'Lorenzo Fernandez',
  'Luciano Gimenez',
  'Martin Diaz',
  'Mariano Roca',
  'Manuel Paez',
  'Matias Herrera',
  'Nicolas Irigoyen',
  'Octavio Ruiz',
  'Pablo Lopez',
  'Pedro Rossi',
  'Rodrigo Mansilla',
  'Tomas Alonso',
  'Facundo Lombardo',
  'Fausto Varela',
  'Esteban Bianchi',
  'Tomas Marino',
  'Francisco Ponce',
  'Pedro Godoy',
  'Agustin Sosa',
  'Mariano Lombardi',
  'Franco Caceres',
  'Tomas Serrano',
  'Jeronimo Aguirre',
];

export const MOCKED_FEMALE_FULL_NAMES = [
  'Abril Gimenez',
  'Agustina Silva',
  'Agostina Ramos',
  'Azul Alonso',
  'Bianca Diaz',
  'Candela Aguilar',
  'Carla Mendez',
  'Clara Alvarez',
  'Celeste Bianchi',
  'Francisca Iglesias',
  'Jazmin Gonzalez',
  'Julia Torres',
  'Julieta Godoy',
  'Josefina Sosa',
  'Laura Mansilla',
  'Lorena Miranda',
  'Luz Castro',
  'Maria Varela',
  'Martina Irigoyen',
  'Micaela Paez',
  'Milagros Avila',
  'Paz Rodriguez',
  'Pilar Fernandez',
  'Rocio Ponce',
  'Rosario Blanco',
  'Valentina Lombardi',
  'Rosario Alvarez',
  'Paz Varela',
  'Francisca Lopez',
  'Jazmin Lopez',
  'Bianca Serrano',
  'Rosario Aguirre',
  'Maria Diaz',
  'Clara Blanco',
  'Pilar Lombardo',
  'Celeste Marino',
  'Valentina Godoy',
  'Azul Diaz',
  'Luz Torres',
  'Julieta Cabrera',
  'Rocio Ferrer',
  'Jazmin Avila',
  'Lorena Lombardi',
  'Luz Ortiz',
  'Micaela Fernandez',
  'Laura Diaz',
  'Juliana Rossi',
  'Martina Cabrera',
  'Josefina Lombardo',
  'Clara Ruiz',
  'Martina Aguirre',
  'Valentina Miranda',
  'Paz Serrano',
  'Azul Lopez',
  'Julia Alonso',
];
